baseURL = "https://blog.lukas-coding.us/"
# disqusShortname = "lherman"
googleAnalytics = "UA-111663256-1"
languageCode = "en-us"
paginate = 5
preserveTaxonomyNames = true
theme = "hugo-nederburg-theme"
title = "Coding and Life"
pygmentsOptions = ""
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[permalinks]
post = "/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
# [[menu.main]]
# name = "About"
# url = "about/"
# weight = 2
# [[menu.main]]
# name = "Get in touch"
# url = "contact/"
# weight = 3

[params]
author = "Lukas Herman"
authorLink = "https://lukas-coding.us"
bio = []
copyright = ["&copy; 2018 Lukas Herman", "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).", "A port of Tracks by Compete Themes."]
description = "Describe your website"
email = "lherman.cs@gmail.com"
slogan = "Thoughts, stories, and ideas."

  [params.social]
  email = "lherman.cs@gmail.com"
  facebook = "https://www.facebook.com/lukashadiyanto"
  github = "https://github.com/lherman-cs"
  googleplus = ""
  instagram = ""
  linkedin = "https://www.linkedin.com/in/lukas-herman/"
  pinterest = ""
  rss = true
  stackoverflow = "https://stackoverflow.com/users/8177592/lukas-herman"
  twitter = "https://twitter.com/lherman_cs"

  [params.writers]
    [params.writers."Lukas Herman"]
    email = "lherman.cs@gmail.com"
    facebook = "https://www.facebook.com/lukashadiyanto"
    github = "https://github.com/lherman-cs"
    googleplus = ""
    instagram = ""
    link = "https://lukas-coding.us"
    linkedin = "https://www.linkedin.com/in/lukas-herman/"
    pinterest = ""
    stackoverflow = "https://stackoverflow.com/users/8177592/lukas-herman"
    twitter = "https://twitter.com/lherman_cs"

    [params.writers."Gabrielle Stewart"]
    email = "gestewa@g.clemson.edu"
    facebook = "https://www.facebook.com/Gaby12345678910"
    linkedin = "https://www.linkedin.com/in/gabrielle-stewart-cs/"
