baseurl = "https://example.org/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 5
preserveTaxonomyNames = true
theme = "hugo-nederburg-theme"
title = "Coding and Life"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "about/"
weight = 2
[[menu.main]]
name = "Get in touch"
url = "contact/"
weight = 3
[params]
author = "Lukas Herman"
authorLink = "https://lherman.tk"
bio = []
copyright = ["&copy; 2018 Lukas Herman", "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).", "A port of Tracks by Compete Themes."]
description = "Describe your website"
email = "lherman.cs@gmail.com"
slogan = "Thoughts, stories, and ideas."
[params.social]
email = "email@example.com"
facebook = "full profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
linkedin = "full profile url in linkedin"
pinterest = "full profile url in pinterest"
rss = true
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
